//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_Recruitment
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedEmployee
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public int Previous_BId { get; set; }
        public int Current_BId { get; set; }
        public string Designation { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
