//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_Recruitment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RecruitmentDBEntities : DbContext
    {
        public RecruitmentDBEntities()
            : base("name=RecruitmentDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessUnitReqTable> BusinessUnitReqTables { get; set; }
        public virtual DbSet<BusinessUnitTable> BusinessUnitTables { get; set; }
        public virtual DbSet<EmployeeDetail> EmployeeDetails { get; set; }
        public virtual DbSet<LoginCredential> LoginCredentials { get; set; }
        public virtual DbSet<tbl_Hireingmanager> tbl_Hireingmanager { get; set; }
        public virtual DbSet<AssignedEmployee> AssignedEmployees { get; set; }
    
        public virtual int proc_add_bunit(string bname)
        {
            var bnameParameter = bname != null ?
                new ObjectParameter("bname", bname) :
                new ObjectParameter("bname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_add_bunit", bnameParameter);
        }
    
        public virtual int proc_add_employee(Nullable<int> eid, string ename, Nullable<int> bid, string des, Nullable<bool> status, Nullable<int> exp)
        {
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            var enameParameter = ename != null ?
                new ObjectParameter("ename", ename) :
                new ObjectParameter("ename", typeof(string));
    
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var desParameter = des != null ?
                new ObjectParameter("des", des) :
                new ObjectParameter("des", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            var expParameter = exp.HasValue ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_add_employee", eidParameter, enameParameter, bidParameter, desParameter, statusParameter, expParameter);
        }
    
        public virtual int proc_delete_BReqTable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_delete_BReqTable");
        }
    
        public virtual ObjectResult<proc_display_businessreq_Result> proc_display_businessreq()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_display_businessreq_Result>("proc_display_businessreq");
        }
    
        public virtual ObjectResult<proc_display_emp_table_Result> proc_display_emp_table()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_display_emp_table_Result>("proc_display_emp_table");
        }
    
        public virtual int proc_insert_req(ObjectParameter rid, Nullable<int> bid, Nullable<int> jreq, Nullable<int> dreq, Nullable<int> breq)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var jreqParameter = jreq.HasValue ?
                new ObjectParameter("jreq", jreq) :
                new ObjectParameter("jreq", typeof(int));
    
            var dreqParameter = dreq.HasValue ?
                new ObjectParameter("dreq", dreq) :
                new ObjectParameter("dreq", typeof(int));
    
            var breqParameter = breq.HasValue ?
                new ObjectParameter("breq", breq) :
                new ObjectParameter("breq", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_insert_req", rid, bidParameter, jreqParameter, dreqParameter, breqParameter);
        }
    
        public virtual int proc_update_tables(Nullable<int> rid, Nullable<int> bid, Nullable<int> eid, string etype)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            var etypeParameter = etype != null ?
                new ObjectParameter("etype", etype) :
                new ObjectParameter("etype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_update_tables", ridParameter, bidParameter, eidParameter, etypeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> proc_login_signin(Nullable<int> eid, string pass, string etype)
        {
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var etypeParameter = etype != null ?
                new ObjectParameter("etype", etype) :
                new ObjectParameter("etype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("proc_login_signin", eidParameter, passParameter, etypeParameter);
        }
    
        public virtual int proc_login_signup(Nullable<int> eid, string pass, string etype)
        {
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var etypeParameter = etype != null ?
                new ObjectParameter("etype", etype) :
                new ObjectParameter("etype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_login_signup", eidParameter, passParameter, etypeParameter);
        }
    
        public virtual ObjectResult<proc_display_requrests_Result> proc_display_requrests(Nullable<int> p_bid)
        {
            var p_bidParameter = p_bid.HasValue ?
                new ObjectParameter("p_bid", p_bid) :
                new ObjectParameter("p_bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_display_requrests_Result>("proc_display_requrests", p_bidParameter);
        }
    
        public virtual ObjectResult<proc_display_available_employees_Result> proc_display_available_employees()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_display_available_employees_Result>("proc_display_available_employees");
        }
    
        public virtual ObjectResult<proc_display_pending_requests_Result> proc_display_pending_requests()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_display_pending_requests_Result>("proc_display_pending_requests");
        }
    
        public virtual ObjectResult<Search_Details_Result> Search_Details(string input_text)
        {
            var input_textParameter = input_text != null ?
                new ObjectParameter("input_text", input_text) :
                new ObjectParameter("input_text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Details_Result>("Search_Details", input_textParameter);
        }
    
        public virtual ObjectResult<Sort_Details_Result> Sort_Details(string input_text)
        {
            var input_textParameter = input_text != null ?
                new ObjectParameter("input_text", input_text) :
                new ObjectParameter("input_text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sort_Details_Result>("Sort_Details", input_textParameter);
        }
    
        public virtual ObjectResult<SortExperience_Result> SortExperience(string exp)
        {
            var expParameter = exp != null ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SortExperience_Result>("SortExperience", expParameter);
        }
    
        public virtual int proc_requiredEmployee(ObjectParameter reqJava, ObjectParameter reqDotNet, ObjectParameter reqBA)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_requiredEmployee", reqJava, reqDotNet, reqBA);
        }
    
        public virtual int proc_updateHRTable(Nullable<int> reqJava, Nullable<int> reqDotNet, Nullable<int> reqBA)
        {
            var reqJavaParameter = reqJava.HasValue ?
                new ObjectParameter("reqJava", reqJava) :
                new ObjectParameter("reqJava", typeof(int));
    
            var reqDotNetParameter = reqDotNet.HasValue ?
                new ObjectParameter("reqDotNet", reqDotNet) :
                new ObjectParameter("reqDotNet", typeof(int));
    
            var reqBAParameter = reqBA.HasValue ?
                new ObjectParameter("reqBA", reqBA) :
                new ObjectParameter("reqBA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_updateHRTable", reqJavaParameter, reqDotNetParameter, reqBAParameter);
        }
    
        public virtual ObjectResult<proc_display_history_table_Result> proc_display_history_table()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_display_history_table_Result>("proc_display_history_table");
        }
    
        public virtual ObjectResult<proc_display_team_Result> proc_display_team(Nullable<int> p_bid)
        {
            var p_bidParameter = p_bid.HasValue ?
                new ObjectParameter("p_bid", p_bid) :
                new ObjectParameter("p_bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_display_team_Result>("proc_display_team", p_bidParameter);
        }
    
        public virtual int proc_insert_history_table(Nullable<int> p_eid, string p_ename, Nullable<int> p_pbid, Nullable<int> p_cbid, string p_des)
        {
            var p_eidParameter = p_eid.HasValue ?
                new ObjectParameter("p_eid", p_eid) :
                new ObjectParameter("p_eid", typeof(int));
    
            var p_enameParameter = p_ename != null ?
                new ObjectParameter("p_ename", p_ename) :
                new ObjectParameter("p_ename", typeof(string));
    
            var p_pbidParameter = p_pbid.HasValue ?
                new ObjectParameter("p_pbid", p_pbid) :
                new ObjectParameter("p_pbid", typeof(int));
    
            var p_cbidParameter = p_cbid.HasValue ?
                new ObjectParameter("p_cbid", p_cbid) :
                new ObjectParameter("p_cbid", typeof(int));
    
            var p_desParameter = p_des != null ?
                new ObjectParameter("p_des", p_des) :
                new ObjectParameter("p_des", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_insert_history_table", p_eidParameter, p_enameParameter, p_pbidParameter, p_cbidParameter, p_desParameter);
        }
    
        public virtual ObjectResult<proc_search_assigned_employee_details_Result> proc_search_assigned_employee_details(string p_text)
        {
            var p_textParameter = p_text != null ?
                new ObjectParameter("p_text", p_text) :
                new ObjectParameter("p_text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_search_assigned_employee_details_Result>("proc_search_assigned_employee_details", p_textParameter);
        }
    
        public virtual ObjectResult<proc_Search_Employee_Team_Result> proc_Search_Employee_Team(string p_text, Nullable<int> p_bid)
        {
            var p_textParameter = p_text != null ?
                new ObjectParameter("p_text", p_text) :
                new ObjectParameter("p_text", typeof(string));
    
            var p_bidParameter = p_bid.HasValue ?
                new ObjectParameter("p_bid", p_bid) :
                new ObjectParameter("p_bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Search_Employee_Team_Result>("proc_Search_Employee_Team", p_textParameter, p_bidParameter);
        }
    
        public virtual ObjectResult<proc_user_details_Result> proc_user_details(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_user_details_Result>("proc_user_details", idParameter);
        }
    }
}
